{{- if eq .Values.global.rabbitmqLocation "on-cluster" }}
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-creds
  labels:
    app: drycc-rabbitmq
    heritage: drycc
  annotations:
    "helm.sh/hook": pre-install
data: 
  cookie: {{ randAscii 64 | b64enc }}
  username: {{ if .Values.username | default "" | ne "" }}{{ .Values.username | b64enc }}{{ else }}{{ randAlphaNum 32 | b64enc }}{{ end }}
  password: {{ if .Values.password | default "" | ne "" }}{{ .Values.password | b64enc }}{{ else }}{{ randAlphaNum 32 | b64enc }}{{ end }}
{{- end }}
