{{- if eq .Values.global.rabbitmqLocation "on-cluster" }}
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-creds
  labels:
    app: drycc-rabbitmq
    heritage: drycc
data: 
  cookie: {{ include "common.secrets.lookup" (dict "secret" "rabbitmq-creds" "key" "cookie" "defaultValue" (randAscii 64) "context" $) }}
  username: {{ .Values.username | b64enc }}
  password: {{ .Values.password | b64enc }}
{{- end }}
