{{- if eq .Values.global.rabbitmqLocation "on-cluster" }}
apiVersion: v1
kind: Service
metadata:
  name: drycc-rabbitmq
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "15692"
    prometheus.io/scrape: "true"
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    heritage: drycc
spec:
  clusterIP: None
  selector:
    app: drycc-rabbitmq
  ports:
  - name: epmd
    port: 4369
    protocol: TCP
    targetPort: 4369
  - name: amqp
    port: 5672
    protocol: TCP
    targetPort: 5672
  - name: metrics
    port: 15692
    protocol: TCP
    targetPort: 15692
  - name: stats
    port: 15672
    protocol: TCP
    targetPort: 15672
  - name: dist
    port: 25672
    protocol: TCP
    targetPort: 25672
{{- end }}
