{{- if eq .Values.global.rabbitmqLocation "on-cluster" }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "drycc-rabbitmq"
  labels:
    app: "drycc-rabbitmq"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    kubernetes.io/tls-acme: "true"
spec:
  {{- if not (eq .Values.global.ingressClass "") }}
  ingressClassName: "{{ .Values.global.ingressClass }}"
  {{ end }}
  rules:
  - host: drycc-rabbitmq.{{ .Values.global.platformDomain }}
    http:
      paths:
      - pathType: Prefix
        {{- if eq .Values.global.ingressClass "gce" "alb" }}
        path: /*
        {{- else }}{{/* Has annotations but ingress class is not "gce" nor "alb" */}}
        path: /
        {{- end }}
        backend:
          service:
            name: drycc-rabbitmq
            port: 
              number: 15672
  {{ if .Values.global.certManagerEnabled }}
  tls:
    - secretName: drycc-rabbitmq-auto-tls
      hosts:
        - drycc-rabbitmq.{{ .Values.global.platformDomain }}
  {{- end }}
{{- end }}