apiVersion: v1
kind: Secret
metadata:
  name: drycc-rabbitmq
  labels:
    heritage: drycc
type: Opaque
data:
  {{- if eq .Values.global.rabbitmq_location "off-cluster" }}
  url: {{ .Values.url | b64enc }}
  {{- end }}
  rabbitmq-password: {{ .Values.password | b64enc }}
  rabbitmq-username: {{ .Values.username | b64enc }}
  vhost: {{ .Values.vhost | b64enc }}
{{- range $key, $value := .Values.extraSecrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $key }}
  labels:
    heritage: drycc
type: Opaque
stringData: {{- $value | toYaml | nindent 2 }}
{{- end }}
