{{- if eq .Values.global.rabbitmqLocation "on-cluster" }}
apiVersion: v1
kind: Service
metadata:
  name: drycc-rabbitmq
  labels:
    heritage: drycc
spec:
  clusterIP: None
  selector:
    app: drycc-rabbitmq
  ports:
  - port: 5672
{{- end }}
