{{- if eq .Values.global.rabbitmqLocation "on-cluster" }}
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-creds
  labels:
    app: drycc-rabbitmq
    heritage: drycc
  annotations:
    "helm.sh/hook": pre-install
data: 
  cookie: {{ randAscii 64 | b64enc }}
  username: {{ .Values.username | b64enc }}
  password: {{ .Values.password | b64enc }}
{{- end }}
