{{- if eq .Values.global.rabbitmq_location "on-cluster" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: drycc-rabitmq-config
  labels:
    heritage: drycc
data:
  rabbitmq.conf: |-
    {{- include "common.tplvalues.render" (dict "value" .Values.configuration "context" $) | nindent 4 }}
  {{- if .Values.advancedConfiguration}}
  advanced.config: |-
    {{- include "common.tplvalues.render" (dict "value" .Values.advancedConfiguration "context" $) | nindent 4 }}
  {{- end }}
{{- end }}