{{- if eq .Values.global.rabbitmqLocation "on-cluster" }}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: drycc-rabbitmq
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - get
{{- end }}