{{- if eq .Values.global.rabbitmq_location "on-cluster" }}
{{- if .Values.rbac.create }}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: drycc-rabbitmq-endpoint-reader
  labels:
    app: drycc-rabbitmq
    heritage: drycc
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create"]
{{- end }}
{{- end }}
