{{- if eq .Values.global.rabbitmq_location "on-cluster" }}
{{- if and .Values.serviceAccount.create .Values.rbac.create }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: drycc-rabbitmq-endpoint-reader
  labels:
    app: drycc-rabbitmq
    heritage: drycc
subjects:
  - kind: ServiceAccount
    name: drycc-rabbitmq
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: drycc-rabbitmq-endpoint-reader
{{- end }}
{{- end }}
