kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: drycc-rabbitmq
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: drycc-rabbitmq
subjects:
- kind: ServiceAccount
  name: drycc-rabbitmq
  namespace: {{ .Release.Namespace }}