{{- if eq .Values.global.rabbitmqLocation "on-cluster" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: drycc-rabbitmq
  labels:
    app: drycc-rabbitmq
    heritage: drycc
secrets:
  - name: drycc-rabbitmq
{{- end }}
