{{- if eq .Values.global.rabbitmqLocation "on-cluster" }}
{{ if .Values.global.certManagerEnabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: drycc-rabbitmq
spec:
  secretName: drycc-rabbitmq-auto-tls
  issuerRef:
    name: drycc-cluster-issuer
    kind: ClusterIssuer
  dnsNames:
  - drycc-rabbitmq.{{ .Values.global.platformDomain }}
  privateKey:
    rotationPolicy: Always
{{- end }}
{{- end }}