{{- if eq .Values.global.rabbitmq_location "on-cluster" }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: drycc-rabbitmq
  labels:
    heritage: drycc
  annotations:
    component.drycc.cc/version: {{ .Values.image_tag }}
spec:
  replicas: 1
  serviceName: drycc-rabbitmq
  selector:
    matchLabels:
      app: drycc-rabbitmq
  template:
    metadata:
      labels:
        app: drycc-rabbitmq
    spec:
      serviceAccount: drycc-rabbitmq
      containers:
        - name: drycc-rabbitmq
          image: {{.Values.image_registry}}/{{.Values.image_org}}/rabbitmq:{{.Values.image_tag}}
          imagePullPolicy: {{.Values.image_pull_policy}}
          ports:
            - containerPort: 5672
{{- if or (.Values.limits_cpu) (.Values.limits_memory)}}
          resources:
            limits:
{{- if (.Values.limits_cpu) }}
              cpu: {{.Values.limits_cpu}}
{{- end}}
{{- if (.Values.limits_memory) }}
              memory: {{.Values.limits_memory}}
{{- end}}
{{- end}}
          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-creds
                  key: username
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-creds
                  key: password
            - name: RABBITMQ_DEFAULT_VHOST
              value: drycc
          lifecycle:
            preStop:
              exec:
                command:
                  - bash
                  - -ec
                  - rabbitmqctl stop_app
          livenessProbe:
            exec:
              command:
                - /bin/bash
                - -ec
                - rabbitmq-diagnostics -q check_running
          readinessProbe:
            exec:
              command:
                - /bin/bash
                - -ec
                - rabbitmq-diagnostics -q check_running
          volumeMounts:
            - name: rabbitmq-creds
              mountPath: /var/run/secrets/drycc/rabbitmq/creds
            {{- if .Values.persistence.enabled }}
            - name: rabbitmq-data
              mountPath: /var/lib/rabbitmq
            {{- end }}
      volumes:
        - name: rabbitmq-creds
          secret:
            secretName: rabbitmq-creds
        {{- if .Values.persistence.enabled }}
        - name: rabbitmq-data
          persistentVolumeClaim:
            claimName: drycc-rabbitmq
        {{- end }}
{{- end }}
