name: rabbitmq
home: https://github.com/drycc/rabbitmq
apiVersion: v2
appVersion: 1.0.0
dependencies:
  - name: common
    repository: oci://registry.drycc.cc/charts
    version: ~1.1.2
description: Open source message broker software that implements the Advanced Message Queuing Protocol (AMQP)
maintainers:
  - name: Drycc Team
    email: engineering@drycc.com
version: v1.0.0
