imageOrg: "drycc"
imagePullPolicy: "Always"
imageTag: "canary"
imageRegistry: "registry.drycc.cc"
## Enable diagnostic mode
##
diagnosticMode:
  ## @param diagnosticMode.enabled Enable diagnostic mode (all probes will be disabled and the command will be overridden)
  ##
  enabled: false
  ## @param diagnosticMode.command Command to override all containers
  ##
  command:
    - sleep
  ## @param diagnosticMode.args Args to override all containers
  ##
  args:
    - infinity
# limits_cpu: "100m"
# limits_memory: "50Mi"
nodeAffinityPreset:
  key: "drycc.cc/node"
  type: "soft"
  values:
  - "true"

podAffinityPreset:
  type: ""
  extraMatchLabels:
    security: "drycc-security"

podAntiAffinityPreset:
  type: "soft"
  extraMatchLabels:
    app: "drycc-rabbitmq"

replicas: 1
# Configure the following ONLY if using an off-cluster rabbitmq
url: "amqp://myuser:mypassword@localhost:5672/myvhost"
# The username and password to be used by the on-cluster database.
# If left empty they will be generated using randAlphaNum
username: "admin"
password: "admin"
# Service
service:
  # Provide any additional service annotations
  annotations: {}
# GCP PDs and EBS volumes are supported only
persistence:
  enabled: false # Set to true to enable persistence
  size: 5Gi # PVC size
  storageClass: ""

global:
  # Set the location of Workflow's rabbitmq instance
  #
  # Valid values are:
  # - on-cluster: Run Rabbitmq within the Kubernetes cluster
  # - off-cluster: Run Rabbitmq outside the Kubernetes cluster (configure in rabbitmq section)
  rabbitmqLocation: "on-cluster"
  clusterDomain: "cluster.local"
  certManagerEnabled: true
